config/routes.rb
Rails.application.routes.draw do
  root "products#index"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  namespace :admin do
    resources :products
    resources :orders do
      member do
        post :cancel
        post :ship
        post :shipped
        post :return
      end
    end
    resources :users do
      member do
        post :to_admin
        post :to_normal
      end
    end
  end

  resources :products do
    member do
      post :add_to_cart
    end
  end

  resources :orders do
    member do
      get :pay_with_credit_card
      post :pay2go_cc_notify
      post :pay2go_atm_complete
    end
  end

  namespace :account do
    resources :orders
  end

  resources :carts do
    collection do
      post :checkout
      delete :clean
    end
  end

  resources :items, controller: "cart_items"

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :cart_items, dependent: :destroy
  has_many :items, through: :cart_items, source: :product

  def find_cart_item(product)
    cart_items.find_by(product_id: product)
  end

  def add_product_to_cart(product)
    ci = cart_items.build
    ci.product = product
    ci.save
  end

  def total_price
    sum = 0

    cart_items.each do |cart_item|
      sum = sum + (cart_item.product.price * cart_item.quantity)
    end

    sum
  end

  def clean!
    cart_items.destroy_all
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!, only: [:checkout]

  def checkout
    @order = current_user.orders.build
    @info = @order.build_info
  end

  def clean
    current_cart.clean!
    flash[:warning] = "購物車已清空"
    redirect_to carts_path
  end
end

app/helpers/carts_helper.rb
module CartsHelper
  def render_cart_total_price(cart)
    cart.total_price
  end
end

app/views/carts/checkout.html.erb
<div class="row">
  <div class="col-md-12">

    <h2> 購物明細 </h2>

    <table class="table table-bordered">
      <thead>
        <tr>
          <th width="80%">商品明細</th>
          <th>數量</th>
          <th>單價</th>
        </tr>
      </thead>
      <tbody>

        <% current_cart.cart_items.each do |item| %>
          <tr>
            <td>
              <%= link_to(item.product.title, product_path(item.product)) %>
            </td>
            <td>
              <%= item.quantity %>
            </td>
            <td>
              <%= item.product.price %>
            </td>
          </tr>
        <% end %>

      </tbody>
    </table>

    <div class="total clearfix">
      <span class="pull-right">
        總計 <%= render_cart_total_price(current_cart) %> NTD
      </span>
    </div>

    <hr>

    <h2> 訂單資訊 </h2>

    <div class="order-form">

      <%= simple_form_for @order do |f| %>

        <%= f.simple_fields_for :info do |c| %>

          <legend> 訂購人 </legend>
          <div class="form-group col-lg-6">
            <%= c.input :billing_name %>
          </div>
          <div class="form-group col-lg-6">
            <%= c.input :billing_address %>
          </div>

          <legend> 收貨人 </legend>
          <div class="form-group col-lg-6">
            <%= c.input :shipping_name %>
          </div>
          <div class="form-group col-lg-6">
            <%= c.input :shipping_address %>
          </div>
        <% end %>

        <div class="checkout">
          <%= f.submit "生成訂單", class: "btn btn-lg btn-danger pull-right",
                       data: { disable_with: "Submitting..." } %>
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/carts/index.html.erb
<div class="wrapper wrapper-content animated fadeInRight">
<div class="row">
    <div class="col-md-9">

        <div class="ibox">
            <div class="ibox-title">
                <span class="pull-right">(<strong><%= render_cart_items_count(current_cart) %></strong>) 商品數 </span>
                <h5>商品明細</h5>
            </div>
            <div class="ibox-content">

              <% current_cart.items.each do |product| %>
                <div class="table-responsive">
                    <table class="table shoping-cart-table">

                        <tbody>
                        <tr>
                            <td width="180">
                                <div class="cart-product-imitation">
                                  <%= link_to product_path(product) do %>
                                    <% if product.photo.present? %>
                                      <%= image_tag(product.photo.image.medium.url, class: "thumbnail") %>
                                    <% else %>
                                      <%= image_tag("http://placehold.it/200x200&text=No Pic", class: " thumbnail") %>
                                    <% end %>
                                <% end %>
                                </div>
                            </td>
                            <td class="desc">
                                <h3>
                                    <a href="#" class="text-navy">
                                      <%= link_to(product.title, product_path(product)) %>
                                    </a>
                                </h3>
                                <p class="small">

                                </p>
                                <dl class="small m-b-none">
                                    <dt>商品說明</dt>
                                    <dd><%= product.description %></dd>
                                </dl>

                                <div class="m-t-sm">
                                    <a href="#" class="text-muted"><i class="fa fa-gift"></i> Add gift package</a>
                                    |
                                    <%= link_to item_path(product), method: :delete do %>
                                    <a href="#" class="text-muted"><i class="fa fa-trash"></i> 刪除商品</a>
                                    <% end %>
                                </div>
                            </td>

                            <td>
                                <%= product.price %>
                                <s class="small text-muted">$230,00</s>
                            </td>
                            <td width="110">
                                <% item = current_cart.find_cart_item(product) %>

                                <%= form_for item, url: item_path(product) do |f| %>
                                  <%= f.select :quantity, 1..product.quantity %>
                                  <%= f.submit "更新", data: { disable_with: "Submiting..." } %>
                                <% end %>
                            </td>
                            <td>
                                <h4>
                                  <%= product.price %>
                                </h4>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </div>
                <hr/>
              <% end %>
            </div>

            <div class="ibox-content">
                <%= link_to checkout_carts_path,
                                    method: :post,
                                    class: "btn btn-primary pull-right" do %>
                          <i class="fa fa-shopping-cart"></i> 確認結賬
                        <% end %>
                <%= link_to products_path do %>
                    <button class="btn btn-white"><i class="fa fa-arrow-left"></i> 繼續購物 </button>
                <% end %>
            </div>
        </div>

    </div>
    <div class="col-md-3">

        <div class="ibox">
            <div class="ibox-title">
                <h5>購物車小記</h5>
            </div>
            <div class="ibox-content">
                            <span>
                                總計
                            </span>
                <h2 class="font-bold">
                    $<%= render_cart_total_price(current_cart) %> NTD
                </h2>

                <hr/>
                            <span class="text-muted small">
                                *For United States, France and Germany applicable sales tax will be applied
                            </span>
                <div class="m-t-sm">
                    <div class="btn-group">
                        <%= link_to checkout_carts_path,
                                    method: :post,
                                    class: "btn btn-primary btn-sm" do %>
                          <i class="fa fa-shopping-cart"></i> 確認結賬
                        <% end %>

                        <%= link_to clean_carts_path,
                                    method: :delete,
                                    class: "btn btn-white btn-sm",
                                    data: { confirm: "你確定要清空整個購物車嗎？"} do %>
                           <i class="fa fa-trash"></i> 清空購物車
                        <% end %>
                    </div>
                </div>
            </div>
        </div>

        <div class="ibox">
            <div class="ibox-title">
                <h5>Support</h5>
            </div>
            <div class="ibox-content text-center">



                <h3><i class="fa fa-phone"></i> +43 100 783 001</h3>
                            <span class="small">
                                Please contact with us if you have any questions. We are avalible 24h.
                            </span>


            </div>
        </div>

        <div class="ibox">
            <div class="ibox-content">

                <p class="font-bold">
                    Other products you may be interested
                </p>

                <hr/>
                <div>
                    <a href="#" class="product-name"> Product 1</a>
                    <div class="small m-t-xs">
                        Many desktop publishing packages and web page editors now.
                    </div>
                    <div class="m-t text-righ">

                        <a href="#" class="btn btn-xs btn-outline btn-primary">Info <i class="fa fa-long-arrow-right"></i> </a>
                    </div>
                </div>
                <hr/>
                <div>
                    <a href="#" class="product-name"> Product 2</a>
                    <div class="small m-t-xs">
                        Many desktop publishing packages and web page editors now.
                    </div>
                    <div class="m-t text-righ">

                        <a href="#" class="btn btn-xs btn-outline btn-primary">Info <i class="fa fa-long-arrow-right"></i> </a>
                    </div>
                </div>

            </div>
        </div>

    </div>
</div>
</div>