config/routes.rb
Rails.application.routes.draw do
  root "products#index"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  namespace :admin do
    resources :products
    resources :orders do
      member do
        post :cancel
        post :ship
        post :shipped
        post :return
      end
    end
    resources :users do
      member do
        post :to_admin
        post :to_normal
      end
    end
  end

  resources :products do
    member do
      post :add_to_cart
    end
  end

  resources :orders do
    member do
      get :pay_with_credit_card
      post :pay2go_cc_notify
      post :pay2go_atm_complete
    end
  end

  namespace :account do
    resources :orders
  end

  resources :carts do
    collection do
      post :checkout
      delete :clean
    end
  end

  resources :items, controller: "cart_items"

end

app/models/product.rb
class Product < ActiveRecord::Base
  has_one :photo

  accepts_nested_attributes_for :photo
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < AdminController

  def index
    @products = Product.all
  end

  def new
    @product = Product.new
    @photo = @product.build_photo
  end

  def edit
    @product = Product.find(params[:id])

    if @product.photo.present?
      @photo = @product.photo
    else
      @photo = @product.build_photo
    end

  end

  def update
    @product = Product.find(params[:id])

    if @product.update(product_params)
      redirect_to admin_products_path
    else
      render :edit
    end
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to admin_products_path
    else
      render :new
    end
  end

  private

  def product_params
    params.require(:product).permit(:title, :description, :quantity, :price,
                                    photo_attributes: [:image, :id])
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def add_to_cart
    @product = Product.find(params[:id])

    if !current_cart.items.include?(@product)
      current_cart.add_product_to_cart(@product)
      flash[:notice] = "你已成功將 #{@product.title} 加入購物車"
    else
      flash[:warning] = "你的購物車內已有此物品"
    end

    redirect_to :back
  end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/index.html.erb
<div class="wrapper wrapper-content animated fadeInRight">

    <div class="row">
        <% @products.each do |product| %>
        <div class="col-md-3">
            <div class="ibox">
                <div class="ibox-content product-box">

                    <div class="product-imitation">
                      <% if product.photo.present? %>
                        <%= image_tag(product.photo.image.thumb.url,) %>
                      <% else %>
                        [ INFO ]
                      <% end %>
                    </div>
                    <div class="product-desc">
                                <span class="product-price">
                                    $ <%= product.price %>
                                </span>
                        <small class="text-muted">Category</small>
                        <div class="product-name"> <%= product.title %> </div>

                        <div class="small m-t-xs">
                            <%= product.description %>
                        </div>
                        <div class="m-t text-righ">
                          <%= link_to product_path(product),
                                      class: "btn btn-xs btn-outline btn-primary" do %>
                            詳細資訊
                            <i class="fa fa-long-arrow-right"></i>
                          <% end %>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <% end %>
        <div style="font-size: 30px;">
        測試帳號：admin@test.com
        <br>
        測試密碼：12345678
        <br>
        如需測試寄信功能，請用有效E-mail註冊，密碼隨意輸入！
        <br>
        信用卡卡號：4000-2222-2222-2222
        <br>
        信用卡末三碼：「任意」
        <br>
        有效年月日：「未來年月」
        </div>
    </div>
</div>

app/views/products/show.html.erb
<div class="wrapper wrapper-content animated fadeInRight">
<div class="row">
    <div class="col-lg-12">

        <div class="ibox product-detail">
            <div class="ibox-content">

                <div class="row">
                    <div class="col-md-5">


                        <div class="product-images">
                            <div>
                                <div class="image-imitation">
                                  <% if @product.photo.present? %>
                                    <%= image_tag(@product.photo.image.medium.url, class: "thumbnail") %>
                                  <% else %>
                                    <%= image_tag("http://placehold.it/400x400&text=No Pic", class: "thumbnail") %>
                                  <% end %>
                                </div>
                            </div>
                        </div>

                    </div>
                    <div class="col-md-7">

                        <h2 class="font-bold m-b-xs">
                            <%= @product.title %>
                        </h2>
                        <small>Many desktop publishing packages and web page editors now.</small>
                        <hr>
                        <div>
                            <% if @product.quantity > 0 %>
                                <%= link_to("Add to cart", add_to_cart_product_path(@product), method: :post, class: "btn btn-primary pull-right") %>
                            <% else %>
                                已銷售一空，無法購買
                            <% end %>
                            <h1 class="product-main-price">
                                NT$ <%= @product.price %>
                                <small class="text-muted">免稅</small>
                            </h1>
                        </div>
                        <hr>
                        <h4>Product description</h4>

                        <div class="small text-muted">
                           <%= @product.description %>
                        </div>

                        <div class="text-right">
                            <div class="btn-group">
                                <button class="btn btn-white btn-sm"><i class="fa fa-star"></i> Add to wishlist </button>
                                <button class="btn btn-white btn-sm"><i class="fa fa-envelope"></i> Contact with author </button>
                            </div>
                        </div>


                    </div>
                </div>

            </div>
            <div class="ibox-footer">
                            <span class="pull-right">
                                Full stock - <i class="fa fa-clock-o"></i> 14.04.2016 10:04 pm
                            </span>
                The generated Lorem Ipsum is therefore always free
            </div>
        </div>

    </div>
</div>




</div>

<% content_for :javascript do %>

<script type="text/javascript">


$(window).load(function() {

    $('.product-images').slick({
        dots: true
    });

});

</script>

<% end %>