config/routes.rb
Rails.application.routes.draw do
  root "products#index"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  namespace :admin do
    resources :products
    resources :orders do
      member do
        post :cancel
        post :ship
        post :shipped
        post :return
      end
    end
    resources :users do
      member do
        post :to_admin
        post :to_normal
      end
    end
  end

  resources :products do
    member do
      post :add_to_cart
    end
  end

  resources :orders do
    member do
      get :pay_with_credit_card
      post :pay2go_cc_notify
      post :pay2go_atm_complete
    end
  end

  namespace :account do
    resources :orders
  end

  resources :carts do
    collection do
      post :checkout
      delete :clean
    end
  end

  resources :items, controller: "cart_items"

end

app/views/layouts/_topnavbar_2.html.erb
<div class="row border-bottom white-bg">
    <nav class="navbar navbar-static-top" role="navigation">
    <div class="navbar-header">
        <button aria-controls="navbar" aria-expanded="false" data-target="#navbar" data-toggle="collapse" class="navbar-toggle collapsed" type="button">
            <i class="fa fa-reorder"></i>
        </button>
        <div class="navbar-brand">
          <%= link_to products_path, style: "color:white" do  %>
            Messmaker
          <% end %>
        </div>
    </div>
    <div class="navbar-collapse collapse" id="navbar">
        <ul class="nav navbar-nav">
            <li class="active">
                <a aria-expanded="false" role="button" href=""> 聯絡我們 </a>
        </li>
        <li class="dropdown">
            <a aria-expanded="false" role="button" href="#" class="dropdown-toggle" data-toggle="dropdown"> 最新情報 <span class="caret"></span></a>
            <ul role="menu" class="dropdown-menu">
                <li><a href="">了解 Messmaker</a></li>
                <li><a href="">最新消息</a></li>
                <li><a href="">優惠活動</a></li>
            </ul>
        </li>
          <li class="dropdown">
            <a aria-expanded="false" role="button" href="#" class="dropdown-toggle" data-toggle="dropdown"> 媒體報導 <span class="caret"></span></a>
                <ul role="menu" class="dropdown-menu">
                    <li><a href="">部落客</a></li>
                    <li><a href="">食尚玩家</a></li>
                    <li><a href="">ＴＶＢＳ</a></li>
                    <li><a href="">壹電視</a></li>
                </ul>
        </li>
        <li class="dropdown">
            <a aria-expanded="false" role="button" href="#" class="dropdown-toggle" data-toggle="dropdown"> Messmaker購物 <span class="caret"></span></a>
            <ul role="menu" class="dropdown-menu">
                <li><a href="">購物說明</a></li>
                <li><a href="">紅利點數說明</a></li>
                <li><a href="">折價卷使用說明</a></li>
                <li><a href="">取消訂單與退換貨</a></li>
            </ul>
        </li>
    </ul>
    <ul class="nav navbar-top-links navbar-right">
        <li>
          <%= link_to carts_path do  %>
            購物車 <i class="fa fa-shopping-cart"> </i> ( <%= render_cart_items_count(current_cart) %> )
          <% end %>
        </li>

        <% if !current_user %>
          <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <i class="fa fa-user"></i>Messmaker服務<b class="caret"></b>
              </a>
            <ul class="dropdown-menu">
              <li>
                <%= link_to new_user_registration_path do %>
                  <i class="fa fa-user-plus"></i> 會員註冊
                <% end %>
              </li>
              <li>
                <%= link_to new_user_session_path do %>
                  <i class="fa fa-sign-in"></i> 會員登入
                <% end %>
              </li>
              <li>
                <%= link_to user_omniauth_authorize_path(:facebook) do %>
                  <i class="fa fa-facebook-official"></i> Facebook登入
                <% end %>
              </li>
            </ul>
          </li>
         <% else %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Hi!, <%= current_user.email %>
                <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <% if current_user.admin? %>
                  <li>
                    <%= link_to("Admin 選單", admin_products_path ) %>
                  </li>
                <% end %>
                  <li>
                    <%= link_to("會員查詢訂單", account_orders_path ) %>
                  </li>
                  <li>
                     <%= link_to("登出", destroy_user_session_path, method: :delete ) %>
                  </li>
              </ul>
            </li>
        <% end %>
    </ul>
</div>
        </nav>
        </div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Messmaker 後台</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="ibox-content product-box">
  <div class="container">
    <%= render "common/navbar" %>
    <%= notice_message %>
    <div class="row">
      <div class="col-md-2">
        <ul class="nav nav-pills nav-stacked" style="max-width: 300px;">
          <li> <%= link_to("Products", admin_products_path) %> </li>
          <li> <%= link_to("Users", admin_users_path) %> </li>
          <li> <%= link_to("Orders", admin_orders_path) %> </li>
        </ul>
      </div>
      <div class="col-md-10">
        <%= yield %>
      </div>
    </div>
  </div>
</div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Welcome Messmaker</title>

    <!-- Include style per-controller - vendor plugins -->
    <%= stylesheet_link_tag params[:controller] if ::Rails.application.assets.find_asset("#{params[:controller]}.css") %>

    <!-- Main css styles -->
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

    <!-- Main javascript files -->
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>



</head>
<body class="top-navigation">

    <!-- Wrapper-->

    <div id="wrapper" class="<%= params[:controller] %>.<%= params[:action] %>">

        <!-- Page wraper -->
        <div id="page-wrapper" class="gray-bg <%= @extra_class %>">

            <!-- Page wrapper -->
            <%= render 'layouts/topnavbar_2' %>
            <!-- Main view  -->
            <%= notice_message %>
            <%= yield %>
            <!-- Footer -->
            <%= render 'common/footer' %>

        </div>
        <!-- End page wrapper-->

    </div>
    <!-- End wrapper-->

    <!-- Include javascript per-controller - vendor plugins -->
    <%= javascript_include_tag params[:controller] if ::Rails.application.assets.find_asset("#{params[:controller]}.js") %>

    <!-- Include javascript per-view -->
    <!-- For demo purpose we include javascript in view but you can easily start SeedProject and organize it with Rails asset pipeline as you want -->
    <%= yield :javascript %>

</body>
</html>